// <auto-generated by DPX-CSharp Samples />
namespace Enterprise.Banking.Domain;

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Channels;
using System.Threading.Tasks;
using Microsoft.Extensions.Options;

// ── 1. Readonly Record Struct & Immutability ────────────────────────────────
public readonly record struct Money(decimal Amount, string Currency)
{
    public static Money Zero(string cur = "USD") => new(0m, cur);
    public static Money From(decimal amt, string cur) => new(amt, cur);
}

public readonly record struct AccountId(Guid Value);
public readonly record struct CustomerId(Guid Value);

// ── 2. Generic Variance (out T Covariance) ──────────────────────────────────
public interface IReadOnlyRepository<out T> where T : class
{
    T? GetById(Guid id);
}

// ── 3. Railway-Oriented Programming (Result Monad) ──────────────────────────
public readonly struct Result<TValue, TError>
{
    public bool IsSuccess { get; }
    public TValue? Value { get; }
    public TError? Error { get; }

    private Result(TValue value)
    {
        IsSuccess = true;
        Value = value;
        Error = default;
    }

    private Result(TError error)
    {
        IsSuccess = false;
        Value = default;
        Error = error;
    }

    public static Result<TValue, TError> Ok(TValue value) => new(value);
    public static Result<TValue, TError> Fail(TError error) => new(error);
}

// ── 4. Options Pattern Configuration ─────────────────────────────────────────
public class BankingOptions
{
    public decimal MaxDailyTransferLimit { get; set; } = 50000m;
    public string DefaultCurrency { get; set; } = "USD";
}

// ── 5. Repository & Unit of Work ────────────────────────────────────────────
public interface IAccountRepository
{
    Task<Account?> FindByIdAsync(AccountId id, CancellationToken ct = default);
    Task SaveAsync(Account account, CancellationToken ct = default);
}

public interface IUnitOfWork
{
    IAccountRepository Accounts { get; }
    Task<int> CommitAsync(CancellationToken ct = default);
}

// ── 6. Domain Entity with Primary Constructor ───────────────────────────────
public class Account(AccountId id, CustomerId ownerId, Money balance)
{
    public AccountId Id { get; } = id;
    public CustomerId OwnerId { get; } = ownerId;
    public Money Balance { get; private set; } = balance;

    public Result<Money, string> Deposit(Money amount)
    {
        if (amount.Amount <= 0)
            return Result<Money, string>.Fail("Deposit must be positive");

        Balance = Balance with { Amount = Balance.Amount + amount.Amount };
        return Result<Money, string>.Ok(Balance);
    }
}

// ── 7. CQRS & MediatR Request Handler ───────────────────────────────────────
public record DepositCommand(AccountId AccountId, Money Amount);

public interface IRequestHandler<in TRequest, TResponse>
{
    Task<TResponse> Handle(TRequest request, CancellationToken cancellationToken);
}

public class DepositCommandHandler(
    IUnitOfWork uow,
    IOptions<BankingOptions> options) : IRequestHandler<DepositCommand, Result<Money, string>>
{
    private readonly BankingOptions _options = options.Value;

    public async Task<Result<Money, string>> Handle(DepositCommand command, CancellationToken cancellationToken)
    {
        var account = await uow.Accounts.FindByIdAsync(command.AccountId, cancellationToken);
        if (account is null)
            return Result<Money, string>.Fail("Account not found");

        var result = account.Deposit(command.Amount);
        if (!result.IsSuccess)
            return result;

        await uow.CommitAsync(cancellationToken);
        return result;
    }
}

// ── 8. Channels (Producer-Consumer Concurrency) ─────────────────────────────
public class TransactionAuditPipeline
{
    private readonly Channel<DepositCommand> _channel = Channel.CreateBounded<DepositCommand>(1000);

    public async Task ProduceAsync(DepositCommand cmd, CancellationToken ct = default)
    {
        await _channel.Writer.WriteAsync(cmd, ct);
    }

    public async IAsyncEnumerable<DepositCommand> ReadAllAsync()
    {
        await foreach (var item in _channel.Reader.ReadAllAsync())
        {
            yield return item;
        }
    }
}
