// <auto-generated by DPX-CSharp Samples />
namespace Enterprise.DesignPatterns.GoF;

using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Threading.Tasks;

// ════════════════════════════════════════════════════════════════════════════
// 1. CREATIONAL PATTERNS (5/5)
// ════════════════════════════════════════════════════════════════════════════

// ── 1.1 Abstract Factory ────────────────────────────────────────────────────
public interface IButton { string Render(); }
public interface IDialog { void Show(); }

public interface IUIFactory
{
    IButton CreateButton();
    IDialog CreateDialog();
}

public class WindowsUIFactory : IUIFactory
{
    public IButton CreateButton() => new WinButton();
    public IDialog CreateDialog() => new WinDialog();
}
public class WinButton : IButton { public string Render() => "<win-btn/>"; }
public class WinDialog : IDialog { public void Show() => Console.WriteLine("Win Dialog"); }

// ── 1.2 Builder Pattern ─────────────────────────────────────────────────────
public class HttpRequestMessageBuilder
{
    private string _url = "";
    private string _method = "GET";

    public HttpRequestMessageBuilder SetUrl(string url) { _url = url; return this; }
    public HttpRequestMessageBuilder SetMethod(string method) { _method = method; return this; }
    public object Build() => new { Url = _url, Method = _method };
}

// ── 1.3 Factory Method ──────────────────────────────────────────────────────
public class ConnectionFactory
{
    public static IDbConnection Create(string type) => type switch
    {
        "sql" => new SqlConnectionImpl(),
        _ => new NpgsqlConnectionImpl()
    };
}
public interface IDbConnection { void Open(); }
public class SqlConnectionImpl : IDbConnection { public void Open() {} }
public class NpgsqlConnectionImpl : IDbConnection { public void Open() {} }

// ── 1.4 Prototype Pattern ───────────────────────────────────────────────────
public class DocumentPrototype : ICloneable
{
    public string Title { get; set; } = "";
    public object Clone() => this.MemberwiseClone();
}

// ── 1.5 Singleton Pattern ───────────────────────────────────────────────────
public class ConfigurationRegistry
{
    private static readonly Lazy<ConfigurationRegistry> _instance = new(() => new ConfigurationRegistry());
    private ConfigurationRegistry() {}
    public static ConfigurationRegistry Instance => _instance.Value;
}

// ════════════════════════════════════════════════════════════════════════════
// 2. STRUCTURAL PATTERNS (7/7)
// ════════════════════════════════════════════════════════════════════════════

// ── 2.1 Adapter Pattern ─────────────────────────────────────────────────────
public interface INewLogger { void LogInfo(string msg); }
public class LegacyLogger { public void Write(string txt) {} }
public class LegacyLoggerAdapter(LegacyLogger legacy) : INewLogger
{
    public void LogInfo(string msg) => legacy.Write(msg);
}

// ── 2.2 Bridge Pattern ──────────────────────────────────────────────────────
public interface IRendererEngine { void RenderShape(); }
public abstract class ShapeBridge(IRendererEngine renderer)
{
    public abstract void Draw();
}
public class CircleShape(IRendererEngine renderer) : ShapeBridge(renderer)
{
    public override void Draw() => renderer.RenderShape();
}

// ── 2.3 Composite Pattern ───────────────────────────────────────────────────
public interface IFileSystemComponent { int GetSize(); }
public class FileLeaf(int size) : IFileSystemComponent { public int GetSize() => size; }
public class DirectoryComposite : IFileSystemComponent
{
    private readonly List<IFileSystemComponent> _children = [];
    public void AddChild(IFileSystemComponent c) => _children.Add(c);
    public void RemoveChild(IFileSystemComponent c) => _children.Remove(c);
    public int GetSize()
    {
        int total = 0;
        foreach (var c in _children) total += c.GetSize();
        return total;
    }
}

// ── 2.4 Decorator Pattern ───────────────────────────────────────────────────
public interface IOrderService { Task ProcessAsync(int orderId); }
public class RealOrderService : IOrderService { public Task ProcessAsync(int id) => Task.CompletedTask; }
public class CachedOrderServiceDecorator(IOrderService inner) : IOrderService
{
    public async Task ProcessAsync(int orderId)
    {
        Console.WriteLine("Checking cache...");
        await inner.ProcessAsync(orderId);
    }
}

// ── 2.5 Facade Pattern ──────────────────────────────────────────────────────
public class PaymentSubsystem { public void Pay() {} }
public class ShippingSubsystem { public void Ship() {} }
public class InventorySubsystem { public void Reserve() {} }
public class OrderCheckoutFacade(PaymentSubsystem pay, ShippingSubsystem ship, InventorySubsystem inv)
{
    public void Checkout()
    {
        inv.Reserve();
        pay.Pay();
        ship.Ship();
    }
}

// ── 2.6 Flyweight Pattern ───────────────────────────────────────────────────
public class GlyphFlyweight(char c) { public char Char { get; } = c; }
public class GlyphPool
{
    private static readonly ConcurrentDictionary<char, GlyphFlyweight> _pool = new();
    public static GlyphFlyweight Get(char c) => _pool.GetOrAdd(c, ch => new GlyphFlyweight(ch));
}

// ── 2.7 Proxy Pattern ───────────────────────────────────────────────────────
public interface IResource { void Fetch(); }
public class SecureResourceProxy(IResource real) : IResource
{
    public void Fetch()
    {
        Console.WriteLine("Authorizing...");
        real.Fetch();
    }
}

// ════════════════════════════════════════════════════════════════════════════
// 3. BEHAVIORAL PATTERNS (11/11)
// ════════════════════════════════════════════════════════════════════════════

// ── 3.1 Chain of Responsibility ─────────────────────────────────────────────
public interface IMiddlewareHandler
{
    Task HandleAsync(object context, Func<object, Task> next);
}
public class AuthMiddleware : IMiddlewareHandler
{
    public async Task HandleAsync(object context, Func<object, Task> next) => await next(context);
}

// ── 3.2 Command Pattern ─────────────────────────────────────────────────────
public interface IAppCommand { void Execute(); }
public class SaveDocumentCommand(DocumentPrototype doc) : IAppCommand
{
    public void Execute() => Console.WriteLine($"Saved: {doc.Title}");
}

// ── 3.3 Interpreter Pattern ─────────────────────────────────────────────────
public interface IExpression { int Interpret(Dictionary<string, int> ctx); }
public class NumberExpression(int n) : IExpression { public int Interpret(Dictionary<string, int> ctx) => n; }

// ── 3.4 Iterator Pattern ────────────────────────────────────────────────────
public class SequenceGenerator
{
    public static IEnumerable<int> Generate()
    {
        yield return 1;
        yield return 2;
        yield return 3;
    }
}

// ── 3.5 Mediator Pattern ────────────────────────────────────────────────────
public class AppEventMediator
{
    private readonly Dictionary<string, List<Action<object>>> _listeners = [];
    public void Subscribe(string ev, Action<object> act)
    {
        if (!_listeners.ContainsKey(ev)) _listeners[ev] = [];
        _listeners[ev].Add(act);
    }
    public void Publish(string ev, object data)
    {
        if (_listeners.TryGetValue(ev, out var list))
            foreach (var a in list) a(data);
    }
}

// ── 3.6 Memento Pattern ─────────────────────────────────────────────────────
public class EditorStateMemento(string text) { public string Text { get; } = text; }
public class TextEditorHistory
{
    private readonly Stack<EditorStateMemento> _history = new();
    public void Save(string state) => _history.Push(new EditorStateMemento(state));
    public string Restore() => _history.Count > 0 ? _history.Pop().Text : "";
}

// ── 3.7 Observer Pattern ────────────────────────────────────────────────────
public class MarketBroadcaster
{
    public event EventHandler<string>? PriceChanged;
    public void Notify(string symbol) => PriceChanged?.Invoke(this, symbol);
}

// ── 3.8 State Pattern ───────────────────────────────────────────────────────
public interface ITrafficState { void Change(TrafficContext ctx); }
public class TrafficContext(ITrafficState initial)
{
    public ITrafficState State { get; set; } = initial;
    public void Request() => State.Change(this);
}
public class RedState : ITrafficState { public void Change(TrafficContext ctx) => ctx.State = new GreenState(); }
public class GreenState : ITrafficState { public void Change(TrafficContext ctx) => ctx.State = new RedState(); }

// ── 3.9 Strategy Pattern ────────────────────────────────────────────────────
public interface ISortingStrategy { void Sort(List<int> list); }
public class QuickSortStrategy : ISortingStrategy { public void Sort(List<int> list) => list.Sort(); }

// ── 3.10 Template Method ────────────────────────────────────────────────────
public abstract class DataProcessorTemplate
{
    public void Process() { ReadData(); Transform(); Output(); }
    protected abstract void ReadData();
    protected virtual void Transform() {}
    protected abstract void Output();
}
public class JsonDataProcessor : DataProcessorTemplate
{
    protected override void ReadData() {}
    protected override void Output() {}
}

// ── 3.11 Visitor Pattern ────────────────────────────────────────────────────
public interface IASTVisitor { void Visit(NumberExpression n); }
public class EvaluatorVisitor : IASTVisitor
{
    public void Visit(NumberExpression n) => Console.WriteLine(n.Interpret([]));
}
