// <auto-generated by DPX-CSharp Samples />
namespace Enterprise.Trading.Engine;

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq.Expressions;
using System.Threading;
using System.Threading.Tasks;

[Flags]
public enum EngineFlags
{
    None = 0,
    HighFrequency = 1 << 0,
    PaperTrading = 1 << 1,
    AuditLogged = 1 << 2
}

public class TradingEngineContext
{
    // ── 1. Mutable Static State Hazard ───────────────────────────────────────
    public static List<string> ActiveOrders = new();

    // ── 2. Async Lock Semaphore ──────────────────────────────────────────────
    private readonly SemaphoreSlim _semaphore = new(1, 1);

    public async Task SafeExecuteTradeAsync()
    {
        await _semaphore.WaitAsync();
        try
        {
            // ── 3. Structured Concurrency Task.WhenAll ───────────────────────
            var taskA = Task.Delay(10);
            var taskB = Task.Delay(10);
            await Task.WhenAll(taskA, taskB);
        }
        finally
        {
            _semaphore.Release();
        }
    }

    // ── 4. Expression Trees & LINQ Filtering ────────────────────────────────
    public void FilterTrades(Expression<Func<string, bool>> filter)
    {
        Console.WriteLine(filter.ToString());
    }

    // ── 5. Hazards & Anti-Patterns ──────────────────────────────────────────
    public void ExecuteDangerousRoutines()
    {
        // 5.1 IDisposable Leak Hazard (Missing using var)
        var stream = new MemoryStream();
        stream.Write([1, 2, 3]);

        // 5.2 Sync-Over-Async Deadlock Hazard
        var result = FetchDataAsync().Result;
        var blocked = FetchDataAsync().GetAwaiter().GetResult();

        // 5.3 Null-Forgiving Suppression Hazard
        string? nullString = null;
        int length = nullString!.Length;

        // 5.4 Blanket Exception Swallowing
        try
        {
            File.ReadAllText("missing.txt");
        }
        catch (Exception)
        {
            // silently swallowed
        }
    }

    private async Task<string> FetchDataAsync()
    {
        await Task.Delay(1);
        return "data";
    }
}
